### PR TITLE
Update testing, types, 0.4 compatibility

### PR DESCRIPTION
**Pull request by garborg**
To turn on Coveralls, all you have to do is sign in to coveralls.io with your github credentials, click 'sync repos' if you're not seeing this one, flip the switch next to this repo to the 'on' position.

I really like how the package was organized so the definitions flowed straight from the spec, very helpful.

### CODE REVIEW

**Comment by yeesian** [comment]
Thanks @garborg, this is great! (:

**Comment by garborg** [comment]
No problem, I'm excited about this package!

**Comment by yeesian** [comment]
@garborg Sorry for the high churn; maybe I should have transferred ownership to JuliaGeo before registering on METADATA. You think it's good to go?

**Comment by garborg** [comment]
Don't be sorry -- you're getting things done. I do think it's good to go. I'll open an issue with migration todos from when I migrated Geodesy.jl.

**Comment by garborg** [comment]
Checklist in issue #4.

**Pull request merged**
